export const GET_POKEMONS         = 'GET_POKEMONS';
export const GET_POKEMONS_REQUEST = 'GET_POKEMONS_REQUEST';
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';
export const GET_POKEMONS_ERROR   = 'GET_POKEMONS_ERROR';

export const GET_POKEMON = 'GET_POKEMON';
